CREATE TABLE IF NOT EXISTS `list` (
  `id` INTEGER PRIMARY KEY,
  `name` varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `list_item` (
  `id` INTEGER PRIMARY KEY,
  `lid` INTEGER NOT NULL,
  `pid` INTEGER NOT NULL,
  `quantity` INTEGER NOT NULL
);